[package]
name = "pathfinding"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array2d = "0.3.2"
image = "0.24.8"
inline_colorization = "0.1.6"
rand = "0.8"
